### ISSUE TITLE
add support for password for user postgres

### ISSUE THREAD

**Issue by liquidat** [matic-insurance/ansible-docker-postgres#10]
Currently the role runs a container with no password set for the user postgres. Thus each and everyone can simply connect to the database with the user postgres with no password.

Please add a line like
```
    env:
      POSTGRES_PASSWORD: "{{ postgres_userpostgres_password }}"
```
to add a password for that user.

**Comment by Kukunin** [comment]
that's pretty critical. all databases, created by this role is open for anonymous access

**Comment by ghost** [comment]
Phew, haven't even seen this issue. I do agree that it could be critical if Postgres port exposed to the external world. @Kukunin will you have time to prepare pull request?

**Comment by Kukunin** [comment]
@vmykhailyk-matic actually, I used a simple role with a single docker_container command in my case:

1. New docker supports named volumes, so there is no need for data containers
2. Official postgres image supports initialization of database/user/password via ENV variables

In my case, it's as simple as 

```yaml
- name: Run PostgreSQL container
  docker_container:
    name: '{{ postgres_container_name }}'
    image: '{{ postgres_docker_image }}'
    restart_policy: always
    state: started
    memory: '{{ postgres_memory_limit | default(omit) }}'
    volumes:
      - '{{ postgres_volume_name }}:/var/lib/postgresql/data'
    env:
      POSTGRES_USER: '{{ postgres_user }}'
      POSTGRES_PASSWORD: '{{ postgres_password }}'
      POSTGRES_DB: '{{ postgres_database }}'
    network_mode: 'host'
```

I'm not sure what PR would be suitable for this package: just a fix of this particular problem or simplifying the code to the single `docker_container` run. The problem with simplifying is the migration from data container to the named volumes, which might be tricky
